# Generated by Django 4.1 on 2022-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMaster',
            fields=[
                ('mobile_key', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(max_length=20)),
                ('mobile_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'general.mobile_master',
            },
        ),
    ]
